api_platform:
    title: Documentation Knowledge Learning 
    description: Site E-learning de formation dans de multiple domaine 
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
